# Generated by Django 4.2 on 2023-04-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_diretor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diretor',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
