# Generated by Django 4.2 on 2023-04-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_director_slug_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='slug',
        ),
    ]
